alexandria/config/routes.rb
Rails.application.routes.draw do

  resource :session




  get "signup" => "users#new"
  resources :users



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root URL -- for now setting to index, but will change once we get more stuff bolted on
  root    "books#index"


  # Books routes
  #get     "books"               => "books#index"
  #get     "books/:id"           => "books#show", as: "book"
  #get     "books/:id/edit"      => "books#edit", as: "edit_book"
  #patch   "books/:id"           => "books#update"

  get       "books/finishedReading"      => "books#finishedReading", as: "finished_reading"
  #get       "books/currentlyReading"     => "books#currentlyReading", as: "currently_reading"
  get       "books/allBooks"              => "books#allBooks", as: "all_books"

  resources :books


end

alexandria/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

alexandria/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user


  def self.getAllBooks(user_id)
    #all
    where(user_id: user_id)
  end


  def self.getCurrentlyReading(user_id)
    where(user_id: user_id).where(date_end: nil).order('id')
  end


  def self.getFinishedReading(user_id)
    where(user_id: user_id).where.not(date_end: nil).order('id')
  end


  validates :name, :date_start, presence: true
  #validates :description, length: { minimum: 25 }

end

alexandria/app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy

  has_secure_password

  validates :username, presence: true, format: /\A\S/, uniqueness: { case_sensitive: false }

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, format: /\A\S+@\S+\z/

  validates :password, length: { within: 10..40, allow_blank: true }


  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end

end

alexandria/app/controllers/api_controller.rb
class ApiController < ApplicationController

  def i18n
    # locale param was defined in config/routes.rb
    render file: "app/assets/i18n/" + params['locale']
  end

end

alexandria/app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]


  def index
    @user_id = current_user
    #@booksCompleteList = Book.getAllBooks
    @booksCurrentlyReading = Book.getCurrentlyReading(@user_id)
    #@booksFinishedReading = Book.getFinishedReading
  end

  def finishedReading
    @user_id = current_user
    @booksFinishedReading = Book.getFinishedReading(@user_id)
  end

  def currentlyReading
    @user_id = current_user
    @booksCurrentlyReading = Book.getCurrentlyReading(@user_id)
  end

  def allBooks
    @user_id = current_user
    @booksCompleteList = Book.getAllBooks(@user_id)
  end


  def show
    @book = Book.find(params[:id])
  end


  def edit
    @book = Book.find(params[:id])
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      #flash[:notice] = "Book Successfully updated!"
      redirect_to @book, notice: "Book successfully updated!"
    else
      render :edit
    end
  end


  def new
    @book = Book.new
  end


  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      #flash[:notice] = "Book Successfully added!"
      #redirect_to @book
      redirect_to books_url, notice: "Book successfully added!"
    else
      render :new
    end

  end


  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_url, alert: "Book deleted!"
    else
      render :destroy
    end
  end



  private

  def require_correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)  || current_user.admin?
      redirect_to root_url
    end
  end


  def book_params
    params.require(:book).
        permit(:name, :description, :chapter, :part_of_series, :date_start, :date_end, :paid)
  end

end

alexandria/app/helpers/api_helper.rb
module ApiHelper
end

alexandria/app/helpers/application_helper.rb
module ApplicationHelper



end

alexandria/app/helpers/books_helper.rb
module BooksHelper
end

alexandria/app/helpers/charts_helper.rb
module ChartsHelper
end

alexandria/app/helpers/dashboard_helper.rb
module DashboardHelper
end

alexandria/app/helpers/elements_helper.rb
module ElementsHelper
end

alexandria/app/helpers/extras_helper.rb
module ExtrasHelper
end

alexandria/app/helpers/forms_helper.rb
module FormsHelper
end

alexandria/app/helpers/maps_helper.rb
module MapsHelper
end

alexandria/app/helpers/multilevel_helper.rb
module MultilevelHelper
end

alexandria/app/helpers/pages_helper.rb
module PagesHelper
end

alexandria/app/helpers/sessions_helper.rb
module SessionsHelper
end

alexandria/app/helpers/tables_helper.rb
module TablesHelper
end

alexandria/app/helpers/users_helper.rb
module UsersHelper


  def profile_image_fullsize(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.username,
              alt: "User Logo",
              width: '160',
              height: '160',
              class: "profile-user-img img-responsive img-circle")
  end



  def profile_image_navbar(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.username,
              alt: "User Logo",
              width: '48',
              height: '48',
              class: "user-image")
  end

end

alexandria/app/helpers/widgets_helper.rb
module WidgetsHelper
end

alexandria/app/views/books/backup/adminlte-orig/_footer.html.erb
<footer class="main-footer">
  <strong>Copyright &copy; <a href="https://www.digitalsynapse.io">Digital Synapse, LLC</a> <%= Time.now.year %>.</strong> All rights reserved.
</footer>

alexandria/app/views/books/backup/adminlte-orig/_navbar.html.erb
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><%= image_tag("logos/logo-64x64_inverted.png", alt: "Digital Synapse Logo", width: '50', height: '50') %></span>

    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><%= image_tag("logos/logo-64x64_inverted.png", alt: "Digital Synapse Logo", width: '50', height: '50') %></span>
  </a>

  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag("icons/users/avatar-white-male_160x160.png", alt: "User Logo", width: '160', height: '160', class: "user-image") %>

            <span class="hidden-xs">Cool Developer</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <img src="../../dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="row">
                <div class="col-xs-4 text-center">
                  <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Friends</a>
                </div>
              </div>
              <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="#" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
      </ul>

    </div>
  </nav>


</header>

alexandria/app/views/books/backup/adminlte-orig/_sidebar_left.html.erb
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag("icons/users/avatar-white-male_160x160.png", alt: "User Logo", width: '160', height: '160', class: "user-image") %>
      </div>
      <div class="pull-left info">
        <p>Cool Developer</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>


    <!-- search form -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
      </div>
    </form>
    <!-- /.search form -->



    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">MAIN NAVIGATION</li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-dashboard"></i> <span>My Dashboard</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="#"><i class="fa fa-circle-o"></i> Reading History</a></li>
          <li><a href="#"><i class="fa fa-circle-o"></i> Rewards History</a></li>
        </ul>
      </li>


      <li class="treeview">
        <a href="#">
          <i class="fa fa-book"></i> <span>My Books</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <%= link_to new_book_path do %>
              <i class="fa fa-circle-o"></i> Add a Book
            <% end %>
          </li>

          <li>
            <%= link_to currently_reading_path do %>
              <i class="fa fa-circle-o"></i> Currently Reading
            <% end %>
          </li>

          <li>
            <%= link_to finished_reading_path do %>
              <i class="fa fa-circle-o"></i> Finished Reading
            <% end %>
          </li>

          <li>
            <%= link_to all_books_path do %>
              <i class="fa fa-circle-o"></i> All Books
            <% end %>
          </li>


        </ul>
      </li>


      <li class="treeview">
        <a href="#">
          <i class="fa fa-pie-chart"></i>
          <span>Charts</span>
          <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="../charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a></li>
          <li><a href="../charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
          <li><a href="../charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
          <li><a href="../charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
        </ul>
      </li>

    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

alexandria/app/views/books/backup/adminlte-orig/_sidebar_right.html.erb
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Create the tabs -->
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>

    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content">
    <!-- Home tab content -->
    <div class="tab-pane" id="control-sidebar-home-tab">
      <h3 class="control-sidebar-heading">Recent Activity</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-birthday-cake bg-red"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

              <p>Will be 23 on April 24th</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-user bg-yellow"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

              <p>New phone +1(800)555-1234</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

              <p>nora@example.com</p>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <i class="menu-icon fa fa-file-code-o bg-green"></i>

            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

              <p>Execution time 5 seconds</p>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

      <h3 class="control-sidebar-heading">Tasks Progress</h3>
      <ul class="control-sidebar-menu">
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Custom Template Design
              <span class="label label-danger pull-right">70%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Update Resume
              <span class="label label-success pull-right">95%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-success" style="width: 95%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Laravel Integration
              <span class="label label-warning pull-right">50%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
            </div>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)">
            <h4 class="control-sidebar-subheading">
              Back End Framework
              <span class="label label-primary pull-right">68%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
            </div>
          </a>
        </li>
      </ul>
      <!-- /.control-sidebar-menu -->

    </div>
    <!-- /.tab-pane -->
    <!-- Stats tab content -->
    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
    <!-- /.tab-pane -->
    <!-- Settings tab content -->
    <div class="tab-pane" id="control-sidebar-settings-tab">
      <form method="post">
        <h3 class="control-sidebar-heading">General Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Report panel usage
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Some information about this general settings option
          </p>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Allow mail redirect
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Other sets of options are available
          </p>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Expose author name in posts
            <input type="checkbox" class="pull-right" checked>
          </label>

          <p>
            Allow the user to show his name in blog posts
          </p>
        </div>
        <!-- /.form-group -->

        <h3 class="control-sidebar-heading">Chat Settings</h3>

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Show me as online
            <input type="checkbox" class="pull-right" checked>
          </label>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Turn off notifications
            <input type="checkbox" class="pull-right">
          </label>
        </div>
        <!-- /.form-group -->

        <div class="form-group">
          <label class="control-sidebar-subheading">
            Delete chat history
            <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
          </label>
        </div>
        <!-- /.form-group -->
      </form>
    </div>
    <!-- /.tab-pane -->
  </div>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

alexandria/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="format-detection" content="telephone=no" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, minimal-ui"/>
  <meta name="keywords" content="" />

  <%= stylesheet_link_tag 'application_back', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="hold-transition skin-blue sidebar-mini">

<% if current_page?("/login") %>
  <%= yield %>
<% else %>
  <div class="wrapper">
    <%= render partial: 'shared/header' %>
    <%= render partial: 'shared/sidebar' %>
    <div class="content-wrapper">
      <%= render partial: 'shared/content_header' %>
      <section class="content">
        <%= render partial: 'shared/messages' %>
        <%= yield %>
      </section>
    </div>
    <%= render partial: 'shared/footer' %>
  </div>
  </body>
<% end %>

<%= javascript_include_tag 'application_back' %>

<% if content_for?(:added_scripts) %>
  <%= yield :added_scripts %>
<% end %>
</html>

alexandria/app/views/layouts/partials/_footer.html.erb
<span>&copy; 2017 - Angle</span>

alexandria/app/views/layouts/partials/_offsidebar.html.erb
<!-- START Off Sidebar (right)-->
<nav>
   <div role="tabpanel">
      <!-- Nav tabs-->
      <ul role="tablist" class="nav nav-tabs nav-justified">
         <li role="presentation" class="active">
            <a href="#app-settings" aria-controls="app-settings" role="tab" data-toggle="tab">
               <em class="icon-equalizer fa-lg"></em>
            </a>
         </li>
         <li role="presentation">
            <a href="#app-chat" aria-controls="app-chat" role="tab" data-toggle="tab">
               <em class="icon-user fa-lg"></em>
            </a>
         </li>
      </ul>
      <!-- Tab panes-->
      <div class="tab-content">
         <div id="app-settings" role="tabpanel" class="tab-pane fade in active">
            <h3 class="text-center text-thin">Tab 1</h3>
         </div>
         <div id="app-chat" role="tabpanel" class="tab-pane fade">
            <h3 class="text-center text-thin">Tab 2</h3>
         </div>
      </div>
   </div>
</nav>
<!-- END Off Sidebar (right)-->

alexandria/app/views/shared/_content_header.html.erb
<section class="content-header">
  <h1> <%= params[:controller].split('/').last.humanize %> </h1>
  <ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> Home </li>
    <li class="active"> <%= params[:controller].split('/').last.humanize %> </li>
  </ol>
</section>

alexandria/app/views/shared/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 0.5.0
  </div>
  <strong>Copyright &copy; <a href="https://www.digitalsynapse.io">Digital Synapse, LLC</a> <%= Time.now.year %>.</strong> All rights reserved.
</footer>

alexandria/app/views/shared/_header.html.erb
<header class="main-header">
  <i src="oops.jpg" class="logo">

    <span class="logo-mini">
      <%= image_tag("logos/alexandria_logo_6_50x50px.png", alt: "Alexandria", width: '50', height: '50') %>
    </span>

    <span class="logo-lg">
    <%= image_tag("logos/alexandria_logo_6_200x50px.png", alt: "Alexandria", width: '200', height: '50') %>
  </i>

  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">


        <% if current_user_admin? %>
          <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag("icons/stickers/admin_icon_purple_256x256.png", alt: "Admin", width: '24', height: '24') %>
            </a>
          </li>
        <% end %>


        <% if current_user %>
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= profile_image_navbar(current_user) %>

              <span class="hidden-xs"><%= current_user.firstname %> <%= current_user.lastname %></span>
            </a>
            <ul class="dropdown-menu">
              <li class="user-header">
                <%= profile_image_fullsize(current_user) %>
                <p>
                  <%= current_user.firstname %> <%= current_user.lastname %>
                  <small>Member since <%= current_user.created_at %></small>
                </p>
              </li>

              <li class="user-footer">
                <div class="pull-left">
                  <%= link_to "Profile", current_user, class: "btn btn-success" %>
                </div>
                <div class="pull-right">
                  <%= link_to "Log Out", session_path, method: :delete, class: "btn btn-danger" %>
                </div>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "sign up", signup_path, class: "button" %>
          </li>
          <li>
            <%= link_to "sign in", new_session_path, class: "button" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

alexandria/app/views/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h4>
        <i class="icon fa fa-<%= name.to_s == 'notice' ? 'check' : 'ban' %>"></i> 
        <%= name.to_s == 'notice' ? 'Success!' : 'Alert!' %>
      </h4>
      <%= content_tag :div, raw(msg.split(",").join("<br>").html_safe), :id => "flash_#{name}" %>
    </div>
    <% flash[name] = nil %>
  <% end %>
<% end %>

alexandria/app/views/shared/_navigation.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Main Menu</h3>
    <nav>
      <ul class="nav masthead-nav">
        <li> hello </li>
        <li> hi there </li>
      </ul>
    </nav>
  </div>
</div>

alexandria/app/views/shared/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <% if current_user %>
      <!--
      <div class="user-panel">

        <div class="pull-left image">
          <%= profile_image_fullsize(current_user) %>
        </div>
        <div class="pull-left info">
          <p><%= current_user.firstname %> <%= current_user.lastname %></p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
              <i class="fa fa-search"></i>
            </button>
          </span>
        </div>
      </form>

      -->

      <ul class="sidebar-menu">
        <!-- <li class="header">MAIN NAVIGATION</li> -->

        <!-- Dashboard Section -->
        <!--
        <li class="treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>My Dashboard</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="#"><i class="fa fa-circle-o"></i> Reading History</a></li>
            <li><a href="#"><i class="fa fa-circle-o"></i> Rewards History</a></li>
          </ul>
        </li>
        -->


        <!-- Books Section -->
        <li class="treeview">
          <a href="#">
            <i class="glyphicon glyphicon-book"></i> <span>My Books</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li>
              <%= link_to new_book_path do %>
                <i class="fa fa-circle-o"></i> Add a Book
              <% end %>
            </li>

            <li>
              <%= link_to books_path do %>
                <i class="fa fa-circle-o"></i> Currently Reading
              <% end %>
            </li>

            <li>
              <%= link_to finished_reading_path do %>
                <i class="fa fa-circle-o"></i> Finished Reading
              <% end %>
            </li>

            <li>
              <%= link_to all_books_path do %>
                <i class="fa fa-circle-o"></i> All Books
              <% end %>
            </li>


          </ul>
        </li>

        <% if current_user_admin? %>
          <!-- Users section -->
          <li class="treeview">
            <a href="#">
              <i class="fa fa-users"></i> <span>Users & Organizations</span>
              <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
              <li>
                <%= link_to users_path do %>
                  <i class="fa fa-circle-o"></i> Show Users
                <% end %>
              </li>

              <li>
                <%= link_to new_user_path do %>
                  <i class="fa fa-circle-o"></i> Add User
                <% end %>
              </li>


            </ul>
          </li>

        <% end %>


        <!-- Charts -- NOT USED RIGHT NOW -->
        <!--
        <li class="treeview">
          <a href="#">
            <i class="fa fa-pie-chart"></i>
            <span>Charts</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="../charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a></li>
            <li><a href="../charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
            <li><a href="../charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
            <li><a href="../charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
          </ul>
        </li>
        -->



      </ul>
    <% end %>
  </section>
</aside>