alexandria/config/routes.rb
Rails.application.routes.draw do

  resource :session




  get "signup" => "users#new"
  resources :users



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root URL -- for now setting to index, but will change once we get more stuff bolted on
  root    "books#index"


  # Books routes
  #get     "books"               => "books#index"
  #get     "books/:id"           => "books#show", as: "book"
  #get     "books/:id/edit"      => "books#edit", as: "edit_book"
  #patch   "books/:id"           => "books#update"

  get       "books/finishedReading"      => "books#finishedReading", as: "finished_reading"
  #get       "books/currentlyReading"     => "books#currentlyReading", as: "currently_reading"
  get       "books/allBooks"              => "books#allBooks", as: "all_books"

  resources :books


end

alexandria/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

alexandria/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user


  def self.getAllBooks(user_id)
    #all
    where(user_id: user_id)
  end


  def self.getCurrentlyReading(user_id)
    where(user_id: user_id).where(date_end: nil).order('id')
  end


  def self.getFinishedReading(user_id)
    where(user_id: user_id).where.not(date_end: nil).order('id')
  end


  validates :name, :date_start, presence: true
  #validates :description, length: { minimum: 25 }

end

alexandria/app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy

  has_secure_password

  validates :username, presence: true, format: /\A\S/, uniqueness: { case_sensitive: false }

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, format: /\A\S+@\S+\z/

  validates :password, length: { within: 10..40, allow_blank: true }


  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end

end

alexandria/app/controllers/api_controller.rb
class ApiController < ApplicationController

  def i18n
    # locale param was defined in config/routes.rb
    render file: "app/assets/i18n/" + params['locale']
  end

end

alexandria/app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]


  def index
    @user_id = current_user
    #@booksCompleteList = Book.getAllBooks
    @booksCurrentlyReading = Book.getCurrentlyReading(@user_id)
    #@booksFinishedReading = Book.getFinishedReading
  end

  def finishedReading
    @user_id = current_user
    @booksFinishedReading = Book.getFinishedReading(@user_id)
  end

  def currentlyReading
    @user_id = current_user
    @booksCurrentlyReading = Book.getCurrentlyReading(@user_id)
  end

  def allBooks
    @user_id = current_user
    @booksCompleteList = Book.getAllBooks(@user_id)
  end


  def show
    @book = Book.find(params[:id])
  end


  def edit
    @book = Book.find(params[:id])
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      #flash[:notice] = "Book Successfully updated!"
      redirect_to @book, notice: "Book successfully updated!"
    else
      render :edit
    end
  end


  def new
    @book = Book.new
  end


  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      #flash[:notice] = "Book Successfully added!"
      #redirect_to @book
      redirect_to books_url, notice: "Book successfully added!"
    else
      render :new
    end

  end


  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_url, alert: "Book deleted!"
    else
      render :destroy
    end
  end



  private

  def require_correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)  || current_user.admin?
      redirect_to root_url
    end
  end


  def book_params
    params.require(:book).
        permit(:name, :description, :chapter, :part_of_series, :date_start, :date_end, :paid)
  end

end

alexandria/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end



  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      #flash[:notice] = "Welcome back #{user.firstname}"
      redirect_to(session[:intended_url] || books_url)
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end



  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed Out!"
  end


end

alexandria/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]



  def index
    @users = User.all
  end


  def show
    @user = User.find(params[:id])
    if not current_user_admin?
      unless session[:user_id] == @user.id
        redirect_to root_url
        return
      end
    end
  end


  def new
    @user = User.new
  end


  def edit
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "User successfully added!"
    else
      render :new
    end

  end


  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      session[:user_id] = nil
      redirect_to users_url, alert: "User deleted!"
    else
      render :destroy
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "User successfully updated!"
    else
      render :edit
    end
  end



  private


  def require_correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)  || current_user.admin?
      redirect_to root_url
    end
  end


  def password_changed?
    !@new_password.blank? or encrypted_password.blank?
  end

  def user_params
    params.require(:user).
        permit(:username, :firstname, :lastname, :email, :password, :password_confirmation)
  end


end

alexandria/app/helpers/api_helper.rb
module ApiHelper
end

alexandria/app/helpers/application_helper.rb
module ApplicationHelper



end

alexandria/app/helpers/books_helper.rb
module BooksHelper
end

alexandria/app/helpers/charts_helper.rb
module ChartsHelper
end

alexandria/app/helpers/dashboard_helper.rb
module DashboardHelper
end

alexandria/app/helpers/documentation_helper.rb
module DocumentationHelper
end

alexandria/app/helpers/elements_helper.rb
module ElementsHelper
end

alexandria/app/helpers/extras_helper.rb
module ExtrasHelper
end

alexandria/app/helpers/forms_helper.rb
module FormsHelper
end

alexandria/app/helpers/maps_helper.rb
module MapsHelper
end

alexandria/app/helpers/multilevel_helper.rb
module MultilevelHelper
end

alexandria/app/helpers/pages_helper.rb
module PagesHelper
end

alexandria/app/helpers/sessions_helper.rb
module SessionsHelper
end

alexandria/app/helpers/tables_helper.rb
module TablesHelper
end

alexandria/app/helpers/users_helper.rb
module UsersHelper


  def profile_image_fullsize(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.username,
              alt: "User Logo",
              width: '160',
              height: '160',
              class: "profile-user-img img-responsive img-circle")
  end



  def profile_image_navbar(user)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
    image_tag(url, alt: user.username,
              alt: "User Logo",
              width: '48',
              height: '48',
              class: "user-image")
  end

end

alexandria/app/helpers/widgets_helper.rb
module WidgetsHelper
end

alexandria/app/views/books/_dashboard.html.erb
<div class="content-heading">
  <!-- START Language list-->
  <div class="pull-right">
    <div class="btn-group">
      <button type="button" data-toggle="dropdown" class="btn btn-default">English</button>
      <ul role="menu" class="dropdown-menu dropdown-menu-right animated fadeInUpShort">
        <li><a href="#" data-set-lang="en">English</a>
        </li>
        <li><a href="#" data-set-lang="es">Spanish</a>
        </li>
      </ul>
    </div>
  </div>
  <!-- END Language list    -->
  Single View
  <small data-localize="dashboard.WELCOME"></small>
</div>
<div class="row">
  <div class="col-xs-12 text-center">
    <h2 class="text-thin">Single view content</h2>
    <p>This project is an application skeleton. You can use it to quickly bootstrap your Ruby on Rails projects and dev environment for these projects.
      <br>The seed app doesn't do much and has most of the feature removed so you can add theme as per your needs just following the demo app examples.</p>
  </div>
</div>

alexandria/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>

  <% if @book.errors.any? %>
    <section id="errors" style="background:lightyellow;">
      <header>
        <h3 style="color:red;">Could not save book!</h3>
        <h4>
          Please correct the following
          <%= pluralize(@book.errors.count, "error") %>:
        </h4>
      </header>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <!-- Book Name -->
  <div class="form-group">
    <%= f.label "Book Title", :class => "" %>
    <% if form_page == "show" %>
      <%= f.text_field :name, autofocus: true, :class => "col-9 form-control", id: 'book-name', disabled: true %>
    <% else %>
      <%= f.text_field :name, autofocus: true, :class => "col-9 form-control", id: 'book-name' %>
    <% end %>
  </div>


  <!-- Book Description -->
  <div class="form-group">
    <%= f.label "Book summary / review", :class => "col-3 col-form-label" %>
    <p>25 character minimum for description</p>
    <% if form_page == "show" %>
      <%= f.text_area :description, rows: 7, :class => "col-9 form-control", id: 'book-description', disabled: true %>
    <% else %>
      <%= f.text_area :description, rows: 7, :class => "col-9 form-control", id: 'book-description' %>
    <% end %>

  </div>


  <!-- Is book a chapter book -->
  <div class="form-group">
    <%= f.label "Is book a chapter book", :class => "col-3 col-form-label"%>
    <!-- <%= f.text_field :chapter, :class => "col-9 form-control"%> -->
    <% if form_page == "show" %>
      <%= f.select :chapter, ['false', 'true'], :class => "col-9", id: 'book-is-chapter-book', disabled: true %>
    <% else %>
      <%= f.select :chapter, ['false', 'true'], :class => "col-9", id: 'book-is-chapter-book' %>
    <% end %>

  </div>


  <!-- Is book part of a series -->
  <div class="form-group">
    <%= f.label "Is the book part of a series", :class => "col-3 col-form-label"%>
    <!-- <%= f.text_field :part_of_series, :class => "col-9 form-control"%> -->
    <% if form_page == "show" %>
      <%= f.select :part_of_series, ['false', 'true'], :class => "col-9", id: 'book-is-part-of-series', disabled: true %>
    <% else %>
      <%= f.select :part_of_series, ['false', 'true'], :class => "col-9", id: 'book-is-part-of-series' %>
    <% end %>

  </div>


  <!-- Date started reading book -->
  <div class="form-group">
    <%= f.label "Date you started reading", :class => "col-3 col-form-label"%>
    <% if form_page == "show" %>
      <%= f.date_field :date_start, :class => "col-9 form-control", id: 'book-date-start-reading', disabled: true %>
    <% else %>
      <%= f.date_field :date_start, :class => "col-9 form-control", id: 'book-date-start-reading' %>
    <% end %>

  </div>


  <!-- Date ended reading book -->
  <div class="form-group">
    <%= f.label "Date you finished the book", :class => "col-3 col-form-label"%>
    <% if form_page == "show" %>
      <%= f.date_field :date_end, :class => "col-9 form-control", id: 'book-date-end', disabled: true %>
    <% else %>
      <%= f.date_field :date_end, :class => "col-9 form-control", id: 'book-date-end' %>
    <% end %>

  </div>


  <!-- Has reward been paid out -->
  <div class="form-group">
    <%= f.label "Has been been paid out", :class => "col-3 col-form-label"%>
    <!-- <%= f.text_field :paid, :class => "col-9 form-control"%> -->
    <% if form_page == "show" %>
      <%= f.select :paid, ['false', 'true'], :class => "col-9", id: 'book-paid-out', disabled: true %>
    <% else %>
      <%= f.select :paid, ['false', 'true'], :class => "col-9", id: 'book-paid-out' %>
    <% end %>

  </div>


  <% if form_page == "show" %>
    <!-- Navigation Buttons -->
    <div class="btn-group">
      <!-- button to edit entry -->
      <%= link_to "Edit Book", edit_book_path(@book), :class => "btn btn-success" %>

      <!-- button to go back to 'all books' -->
      <%= link_to "All Books", books_path, :class => "btn btn-primary" %>

      <!-- button to delete -->
      <%= link_to "Delete", book_path(@book), method: :delete,
                  data: {confirm:  "Are you sure?"},
                  :class => "btn btn-danger" %>
    </div>
  <% else %>
    <!-- Navigation Buttons -->
    <div class="btn-group">

      <%= f.submit :class => "btn btn-primary", id: 'button-submit' %>


      <!-- button to cancel editing entry -->
      <%= link_to "Cancel", books_path, :class => "btn btn-default", id: 'button-cancel' %>

    </div>
    <!-- End Navigation Buttons -->
  <% end %>

<% end %>

alexandria/app/views/books/_reading_list.html.erb
<% book_query = @booksCompleteList if local_assigns[:book_query].nil? %>

<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title"><%= pluralize(book_query.size, 'Book') %></h3>



    <% if book_query.size > 0 %>

      <!-- /.box-header -->
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">

          <% book_query.each do |book| %>
            <td style="width:50%"><%= link_to truncate(book.name, length: 60, separator: ' '), book %></td>
            <td style="width:30%"><%= link_to truncate(book.description, length: 40, separator: ' '), book %></td>


            <!-- Book badges section -->
            <td style="width:20%">
              <!-- Is book a chapter book -->
              <% if book.chapter? %>
                <!-- <td style="text-align: center;"><i class="fa fa-book" aria-hidden="true"></i></td> -->
                <%= image_tag("icons/flat/book_chapter_color.svg", alt: "Chapter Book", width: '16', height: '16', title: "Is a chapter book") %>
              <% else %>
                <%= image_tag("icons/flat/book_nochapter_color.svg", alt: "Non-Chapter Book", width: '16', height: '16', title: "Is not a chapter book") %>
              <% end %>


              <!-- Is book part of a series -->
              <% if book.part_of_series %>
                <%= image_tag("icons/flat/book_series_color.svg", alt: "Chapter Book", width: '16', height: '16', title: "Part of a series") %>
              <% else %>
                <%= image_tag("icons/flat/book_series_color.svg", alt: "Chapter Book", width: '16', height: '16', style: "filter: grayscale(100%);", title: "Not part of a series") %>
              <% end %>


              <!-- Has been been paid -->
              <% if book.paid? %>
                <!-- <td style="text-align: center;"> -->
                <!-- <%= image_tag("icons/flat/badge_rewarded.svg", alt: "Non-Chapter Book", width: '16', height: '16', title: "Has been paid") %> -->
                <i style="color:green;" class="fa fa-gift" title="Has been paid"></i>
                <!-- </td> -->
              <% else %>
                <!-- <td style="text-align: center; filter: grayscale(100%);"> -->
                <!-- <%= image_tag("icons/flat/badge_rewarded.svg", alt: "Non-Chapter Book", width: '16', height: '16', title: "has not been paid") %> -->
                <i class="fa fa-gift" title="Has not been paid"></i>
                <!-- </td> -->
              <% end %>

            </td>

            </tr>
          <% end %>

        </table>
      </div>
      <!-- /.box-body -->
    <% end %>

  </div>
</div>

alexandria/app/views/books/_reading_list_detailed.html.erb
<% book_query = @booksCompleteList if local_assigns[:book_query].nil? %>

<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title"><%= pluralize(book_query.size, 'Book') %></h3>



    <% if book_query.size > 0 %>

      <!-- /.box-header -->
      <div class="box-body">
        <% book_query.each do |book| %>
          <h3><%= link_to truncate(book.name, length: 60, separator: ' '), book %></h3>
          <h4>
            Book Description
          </h4>
          <p>
            <%= truncate(book.description, length: 40, separator: ' ') %>
          </p>

          <h4>
            Badges
          </h4>

          <p>
            <% if book.chapter? %>
              <!-- <td style="text-align: center;"><i class="fa fa-book" aria-hidden="true"></i></td> -->
              <%= image_tag("icons/flat/book_chapter_color.svg", alt: "Chapter Book", width: '16', height: '16', title: "Is a chapter book") %>
            <% else %>
              <%= image_tag("icons/flat/book_nochapter_color.svg", alt: "Non-Chapter Book", width: '16', height: '16', title: "Is not a chapter book") %>
            <% end %>


            <!-- Is book part of a series -->
            <% if book.part_of_series %>
              <%= image_tag("icons/flat/book_series_color.svg", alt: "Chapter Book", width: '16', height: '16', title: "Part of a series") %>
            <% else %>
              <%= image_tag("icons/flat/book_series_color.svg", alt: "Chapter Book", width: '16', height: '16', style: "filter: grayscale(100%);", title: "Not part of a series") %>
            <% end %>


            <!-- Has been been paid -->
            <% if book.paid? %>
              <!-- <td style="text-align: center;"> -->
              <!-- <%= image_tag("icons/flat/badge_rewarded.svg", alt: "Non-Chapter Book", width: '16', height: '16', title: "Has been paid") %> -->
              <i style="color:green;" class="fa fa-gift" title="Has been paid"></i>
              <!-- </td> -->
            <% else %>
              <!-- <td style="text-align: center; filter: grayscale(100%);"> -->
              <!-- <%= image_tag("icons/flat/badge_rewarded.svg", alt: "Non-Chapter Book", width: '16', height: '16', title: "has not been paid") %> -->
              <i class="fa fa-gift" title="Has not been paid"></i>
              <!-- </td> -->
            <% end %>
          </p>
          <!-- Book badges section -->
          <!-- Is book a chapter book -->


          <br>

          <% end %>

      </div>
      <!-- /.box-body -->
    <% end %>

  </div>
</div>

alexandria/app/views/books/allBooks.html.erb
<%= render 'reading_list', book_query: @booksCompleteList %>

alexandria/app/views/books/backup/_header.html.erb
<head>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">


</head>

alexandria/app/views/books/backup/_navbar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark">

  <!-- Brand logo -->
  <a class="navbar-brand" href="/">
    <%= image_tag("logos/logo-64x64_inverted.png", alt: "Digital Synapse Logo", width: '24', height: '24') %> Alexandria
  </a>



</nav>

alexandria/app/views/books/backup/_sidebar.html.erb
<ul class="sidebar-nav">
  <li class="sidebar-brand">
    <a href="#">
      Books
    </a>
  </li>
  <li>
    <%= link_to "Add Book", new_book_path %>
  </li>

  <li>
    <%= link_to "Add Book", new_book_path %>
  </li>

  <li>
    <%= link_to "Add Book", new_book_path %>
  </li>
</ul>

alexandria/app/views/books/currentlyReading.html.erb
<%= render 'reading_list', book_query: @booksCurrentlyReading %>

alexandria/app/views/books/edit.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Edit Your Book</h3>

    <%= render 'form', form_page: "edit" %>

  </div>
</div>

alexandria/app/views/books/finishedReading.html.erb
<%= render 'reading_list', book_query: @booksFinishedReading %>

alexandria/app/views/books/index.html.erb
<%= render 'reading_list', book_query: @booksCurrentlyReading %>

alexandria/app/views/books/new.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Add a New Book</h3>

    <%= render 'form', form_page: "new" %>

  </div>
</div>

alexandria/app/views/books/show.html.erb
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Book Information</h3>

    <%= render 'form', form_page: "show" %>

  </div>
</div>

alexandria/app/views/users/_form.html.erb
<div class="form-group">
  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control", placeholder: "User name", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :firstname %>
  <%= f.text_field :firstname, class: "form-control", placeholder: "First name", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :lastname %>
  <%= f.text_field :lastname, class: "form-control", placeholder: "Last name", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control", placeholder: "Enter email", required: true %>
  <span class="help-block"><i>* This field is required</i><span>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control", placeholder: "Enter password", required: (@user.new_record? ? true : false) %>
  <span class="help-block"><i>* This field is required (leave blank if you are editing and don't want to change the password)</i><span>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password", required: (@user.new_record? ? true : false) %>
  <span class="help-block"><i>* This field is required (leave blank if you are editing and don't want to change the password)</i><span>
</div>

alexandria/app/views/users/_user_profile.html.erb
<%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <section id="errors" style="background:lightyellow;">
      <header>
        <h3 style="color:red;">Could not save user!</h3>
        <h4>
          Please correct the following
          <%= pluralize(@user.errors.count, "error") %>:
        </h4>
      </header>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </section>
  <% end %>


  <%= form_for @user, url: @url, role: :form, html: { multipart: true } do |f| %>


    <div class="box">

      <div class="box-header">
        <h3 class="box-title">User Information</h3>
      </div>

      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#profile" data-toggle="tab">Profile</a></li>
          <li><a href="#organizations" data-toggle="tab">Organizations</a></li>
        </ul>

        <div class="tab-content">
          <div class="active tab-pane" id="profile">
            <div class="row">
              <div class="col-md-8">
                <%= render partial: 'form', locals: { f: f } %>
              </div>

              <div class="col-md-4">



                <% if @user.new_record? %>
                  <%= image_tag("icons/users/avatar-white-male_160x160.png", alt: "User Logo", width: '160', height: '160', class: "user-image") %>
                <% else %>
                  <%= profile_image_fullsize(@user) %>
                <% end %>

              </div>


            </div>


          </div>

          <div class="activity tab-pane" id="organizations">
            <p>nothing to show here</p>
          </div>

          <% if form_page == "show" %>
            <% if current_user?(@user) %>
              <!-- Navigation Buttons -->
              <div class="btn-group">
                <!-- button to edit entry -->
                <%= link_to "Edit User", edit_user_path(@user), :class => "btn btn-success" %>

                <!-- button to go back to 'all books' -->
                <%= link_to "All Users", users_path, :class => "btn btn-primary" %>

                <!-- button to delete -->
                <%= link_to "Delete User", user_path(@user), method: :delete,
                            data: {confirm:  "Are you sure?"},
                            :class => "btn btn-danger" %>
              </div>
            <% end %>

            <% if current_user_admin? %>
              <!-- Navigation Buttons -->
              <div class="btn-group">
                <!-- button to edit entry -->
                <%= link_to "Edit User", edit_user_path(@user), :class => "btn btn-success" %>

                <!-- button to go back to 'all books' -->
                <%= link_to "All Users", users_path, :class => "btn btn-primary" %>

                <!-- button to delete -->
                <%= link_to "Delete User", user_path(@user), method: :delete,
                            data: {confirm: "Are you sure?"},
                            :class => "btn btn-danger" %>
              </div>

            <% end %>

          <% else %>


              <!-- Navigation Buttons -->
              <div class="btn-group">

                <%= f.submit :class => "btn btn-primary", id: 'button-submit' %>

                <!-- button to cancel editing entry -->
                <%= link_to "Cancel", users_path, :class => "btn btn-default", id: 'button-cancel' %>

              </div>
              <!-- End Navigation Buttons -->

          <% end %>

        </div>

      </div>



    </div>


  <% end %>




<% end %>

alexandria/app/views/users/edit.html.erb
<%= render 'user_profile', form_page: "edit" %>

alexandria/app/views/users/index.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title"><%= pluralize(@users.size, 'User') %></h3>

    <% if @users.size > 0 %>

      <!-- /.box-header -->
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">

          <thead>
          <tr>
            <th>ID</th>
            <th>Username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email Address</th>
            <th>Created At</th>
          </tr>
          </thead>
          <% @users.each do |user| %>
            <tr> <!-- start each user on new row -->
              <td><%= user.id %></td>
              <td><%= link_to user.username, user %></td>
              <td><%= user.firstname %></td>
              <td><%= user.lastname %></td>
              <td><%= user.email %></td>
              <td><%= user.created_at %></td>

            </tr> <!-- end each user row -->


          <% end %>

        </table>
      </div>
      <!-- /.box-body -->
    <% end %>



  </div>
</div>

alexandria/app/views/users/new.html.erb
<%= render 'user_profile', form_page: "new" %>

alexandria/app/views/users/show.html.erb
<%= render 'user_profile', form_page: "show" %>